In [14]:
import os
import pandas as pd
import numpy as np
from PIL import Image
import io
from io import BytesIO
from cellpose import models, io
from cellpose.io import imread
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from skimage import io, transform

In [15]:
model = models.CellposeModel(gpu=False, model_type='cyto')

model_type argument is not used in v4.0.1+. Ignoring this argument...


In [16]:
try:
    img = io.imread('NGS_7504.jpg')
    print(type(img))
    print("Image shape:")
    print(img.shape)
    print(img)

    masks, flows, diams = model.eval(img, channels=[0, 0], diameter=None, augment=True)
    print("Strings: Masks" + str(masks) + " Flows" + str(flows) + " Diams" + str(diams))
    print("Types:" + str(type(masks)) + " " + str(type(flows)) + " " + str(type(diams)))
    np.save('mask.npy', masks)

    try:

        for i in range(1, masks.max()+1):
            mask = masks == i  # Get mask for cell i

            # Find bounding box for this mask
            coords = np.argwhere(mask)
            y0, x0 = coords.min(axis=0)
            y1, x1 = coords.max(axis=0)

            # Crop original image using bounding box
            cropped = img[y0:y1+1, x0:x1+1]

            # Optional: apply mask to cropped image (zero out background)
            mask_cropped = mask[y0:y1+1, x0:x1+1]
            cropped_masked = cropped.copy()
            cropped_masked[~mask_cropped] = 0

            all_cells.append(cropped_masked)

    except Exception as e:
        print(e)

except Exception as e:
    print(e)

plt.imshow(all_cells[1])
plt.show()


channels deprecated in v4.0.1+. If data contain more than 3 channels, only the first 3 channels will be used


<class 'numpy.ndarray'>
Image shape:
(400, 400, 3)
[[[200 165 185]
  [196 161 181]
  [196 161 181]
  ...
  [171 131 166]
  [171 131 165]
  [171 131 165]]

 [[200 165 185]
  [197 162 182]
  [198 163 183]
  ...
  [171 131 165]
  [172 132 166]
  [172 132 166]]

 [[198 163 183]
  [197 162 182]
  [197 162 182]
  ...
  [173 136 169]
  [173 136 169]
  [173 136 167]]

 ...

 [[219 192 207]
  [220 193 208]
  [218 194 208]
  ...
  [236 230 232]
  [236 230 232]
  [236 230 232]]

 [[219 190 208]
  [217 190 207]
  [215 191 207]
  ...
  [232 228 229]
  [233 229 230]
  [235 231 232]]

 [[219 190 208]
  [216 189 206]
  [214 187 204]
  ...
  [232 228 229]
  [233 229 230]
  [233 229 230]]]
Strings: Masks[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [11 11 11 ...  0  0  0]
 [ 0 11 11 ...  0  0  0]
 [ 0 11 11 ...  0  0  0]] Flows[array([[[  9,  89,  41],
        [  6,  93,  49],
        [  4,  94,  57],
        ...,
        [  7,  17,  47],
        [  8,  14,  45],
     

NameError: name 'all_cells' is not defined

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,